### PR TITLE
Added reset_bot function

### PR DESCRIPTION
**Pull request by Eikosa**

### CODE REVIEW

**Comment by Eikosa** [comment]
The edited code gives the following error:
image

**Comment by scmanjarrez** [comment]
Can you give execution permissions to edge.py? I think you're running it like python src/edge.py, right?

**Comment by Eikosa** [comment]
Yes I run it as src/edge.py because if I run it directly it gives an error like this.
```console
root@kelime:~/EdgeGPT-Telegram-Bot/src# sudo python3 edge.py 
Traceback (most recent call last):
  File "/root/EdgeGPT-Telegram-Bot/src/edge.py", line 302, in <module>
    f"{ut.PATH['config']} or {ut.PATH['cookies']} file missing."
KeyError: 'cookies'
```

When I typed chown, it gave the following error
```console
root@kelime:~/EdgeGPT-Telegram-Bot# chown +x src/edge.py
chown: invalid user: ‘+x
```

The problem was solved when I did the following
```console
root@kelime:~/EdgeGPT-Telegram-Bot# sudo chmod +x src/edge.py
root@kelime:~/EdgeGPT-Telegram-Bot# sudo python3 src/edge.py 
2023-06-03 15:50:43,488 - apscheduler.scheduler - INFO - Scheduler started
2023-06-03 15:50:43,488 - telegram.ext._application - INFO - Application started
2023-06-03 15:50:46,381 - apscheduler.scheduler - INFO - Scheduler started
2023-06-03 15:50:46,382 - telegram.ext._application - INFO - Application started
```

**Comment by scmanjarrez** [comment]
Oh, I forgot about that code in edge.py. Btw, it's chmod, not chown, sorry, I mistyped it.

**Comment by scmanjarrez** [comment]
Ok, try again; edge.py should have execution permissions, and you should run it from the root of the repository:

```bash
❯ ls src
drwxrwxr-x zuzu zuzu 4.0 KB Sat Jun  3 15:04:47 2023  __pycache__
.rw-rw-r-- zuzu zuzu  13 KB Sat Jun  3 13:16:18 2023  backend.py
.rw-rw-r-- zuzu zuzu  24 KB Sat Jun  3 15:15:14 2023  cmds.py
.rw-rw-r-- zuzu zuzu 5.5 KB Sat Jun  3 13:16:18 2023  database.py
.rwxrwxr-x zuzu zuzu 9.8 KB Sat Jun  3 15:15:14 2023  edge.py
.rw-rw-r-- zuzu zuzu  11 KB Sat Jun  3 13:16:18 2023  utils.py

❯ src/edge.py
2023-06-03 15:18:40,516 - apscheduler.scheduler - INFO - Scheduler started
2023-06-03 15:18:40,516 - telegram.ext.Application - INFO - Application started
^C2023-06-03 15:18:41,166 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2023-06-03 15:18:41,167 - apscheduler.scheduler - INFO - Scheduler has been shut down
2023-06-03 15:18:41,178 - telegram.ext.Application - INFO - Application.stop() complete
```

**Comment by Eikosa** [comment]
When I tried it, I had the following problem, but it works when i try the next dir (EdgeGPT-Telegram-Bot):
```python3
root@kelime:~/EdgeGPT-Telegram-Bot# cd src/
root@kelime:~/EdgeGPT-Telegram-Bot/src# sudo python3 edge.py 
Traceback (most recent call last):
  File "/root/EdgeGPT-Telegram-Bot/src/edge.py", line 302, in <module>
    f"{ut.PATH['config']} or {ut.PATH['cookies']} file missing."
KeyError: 'cookies'
root@kelime:~/EdgeGPT-Telegram-Bot/src# src/edge.py
bash: src/edge.py: No such file or directory
root@kelime:~/EdgeGPT-Telegram-Bot/src# 
```

**Comment by scmanjarrez** [comment]
Yes, you have to invoke it from the root of the repository (EdgeGPT-Telegram-Bot)

**Pull request merged**
